minimum_pre_commit_version: 2.11.0
default_stages: [commit, push, manual]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=800]
      - id: debug-statements
      - id: mixed-line-ending
      - id: trailing-whitespace
